const {test}=require('node:test');
const assert=require('node:assert/strict');
const S=require('../js/state'), R=require('../js/rules'), Sheet=require('../js/character-sheet');
const {RoomManager}=require('../server/room-manager');
const fresh=()=>S.createStore({storage:null});
function setup(){const m=new RoomManager(),{room}=m.create('h',{}),{session}=m.join('p',{roomCode:room.code,displayName:'Bob'});const id=room.gameState.selectedCharacterId;m.assign('h',{playerId:session.playerId,characterId:id});return {m,room,id,session,act:(action,args,socket='h')=>m.action(socket,{action,args,baseVersion:room.gameVersion})};}
function config(id){return {characterId:id,aspectId:'courage',manualTn:false,difficultyModifier:1,edges:0,flaws:0,forcedOmen:false,risky:false,harmless:false};}
for(const [rating,tn] of Object.entries({Terrible:10,Bad:9,Average:7,Good:5,Great:4})) test(`Save and server Check: ${rating} → ${tn}`,()=>{const {m,room,id,act}=setup();const aspects=structuredClone(room.gameState.characters[0].aspects);aspects[0].rating=rating;act('editCharacter',[id,{aspects}],'p');const c=room.gameState.characters[0];assert.equal(c.aspects[0].rating,rating);assert.equal(R.getTargetNumberForRating(rating),tn);for(const editable of [true,false])assert.match(Sheet.markup(room.gameState,c,editable),new RegExp(`data-tn>TN ${tn}`));m.checks.create('h',{configuration:config(id),baseVersion:room.gameVersion});assert.equal(room.gameState.currentCheck.configuration.baseTn,tn);assert.equal(room.gameState.currentCheck.finalTn,tn+1);});
test('Player own-sheet only; setting OFF; protected mechanics and invalid slots reject atomically',()=>{const {room,id,act}=setup();act('addCharacter',[]);const other=room.gameState.characters[1].id;assert.throws(()=>act('editCharacter',[other,{name:'Spoof'}],'p'));for(const patch of [{wounds:0},{strain:{}},{active:true},{cheatDeathUsed:false},{safeDiceLost:0},{playerId:'x'},{tn:1},{aspects:[]},{aspects:room.gameState.characters[0].aspects.map(a=>({...a,rating:'Amazing'}))},{aspects:room.gameState.characters[0].aspects.map(a=>({...a,strained:true}))}]){const before=structuredClone(room.gameState);assert.throws(()=>act('editCharacter',[id,patch],'p'));assert.deepEqual(room.gameState,before);}act('setSetting',['allowPlayerCharacterEdits',false]);assert.throws(()=>act('editCharacter',[id,{name:'No'}],'p'));act('editCharacter',[id,{name:'Host still edits'}]);assert.doesNotMatch(Sheet.markup(room.gameState,room.gameState.characters[0],false,'Bob',false),/data-save|data-strain=/);});
test('Full sheet save, stable entries, usage, session roundtrip and reconnect',()=>{const {m,room,id,session,act}=setup(),aspects=structuredClone(room.gameState.characters[0].aspects);aspects[0].rating='Good';aspects[2].rating='Bad';aspects[5].name='Occultism';aspects[5].rating='Great';act('editCharacter',[id,{name:'Jasper',archetype:'Scholar',description:'A survivor',notes:'',aspects,perks:[{id:'bossy-entry',name:'Bossy',notes:'Lead',ruleKey:'bossy',disabled:false},{id:'manual',name:'Custom',notes:'',ruleKey:null,disabled:false}],gear:[{id:'flashlight',name:'Flashlight',notes:'Bright'}]}],'p');act('setStrain',[id,'story-1',true]);const before=structuredClone(room.gameState);m.disconnect('p');m.reconnect('p2',session);assert.deepEqual(room.gameState,before);const s=fresh();s.importState(before);assert.deepEqual(s.getState().characters,before.characters);act('editCharacter',[id,{gear:[{id:'flashlight',name:'Flashlight',notes:'New batteries'}]}],'p2');assert.equal(room.gameState.characters[0].gear[0].id,'flashlight');act('editCharacter',[id,{gear:[]}],'p2');assert.equal(room.gameState.characters[0].gear.length,0);});
test('Full sheet save during pending Check preserves snapshot and next Check uses saved Rating',()=>{const {m,room,id,act}=setup();m.checks.create('h',{configuration:config(id),baseVersion:room.gameVersion});const c=structuredClone(room.gameState.characters[0]),snapshot=structuredClone(room.gameState.currentCheck);c.aspects[0].rating='Good';act('editCharacter',[id,{name:c.name,aspects:c.aspects,perks:c.perks,gear:c.gear,notes:''}],'p');assert.deepEqual(room.gameState.currentCheck,snapshot);m.checks.handle('h','check:cancel',{checkId:snapshot.id,baseVersion:room.gameVersion});m.checks.create('h',{configuration:config(id),baseVersion:room.gameVersion});assert.equal(room.gameState.currentCheck.configuration.baseTn,5);});
function populated(){const s=fresh(),id=s.getState().selectedCharacterId,c=s.getState().characters[0];c.aspects[0].rating='Good';c.aspects[5].name='Occultism';s.editCharacter(id,{name:'Jasper',archetype:'Scholar',description:'Desc',notes:'Notes',aspects:c.aspects,perks:[{id:'bossy',name:'Bossy',notes:'Lead',ruleKey:'bossy',disabled:true}],gear:[{id:'torch',name:'Flashlight',notes:'Bright'}]});s.setStrain(id,'story-1',true);const state=s.getState();state.characters[0].wounds=2;state.characters[0].cheatDeathUsed=true;state.characters[0].perkUsage.bossy={storyUsed:false,actsUsed:['Act 1'],scenesUsed:[1]};state.hostOmens=11;s.importState(state);return s;}
test('Character export allowlist excludes room/auth secrets at every structured level',()=>{const s=populated(),state=s.getState(),c=state.characters[0];for(const key of ['roomCode','playerId','reconnectToken','socketId','hostId','pendingCheck','bag'])c[key]='secret';c.aspects[0].socketId='secret';c.perks[0].reconnectToken='secret';c.perkUsage.bossy.socketId='secret';s.importState(state);const file=s.exportCharacter(c.id),json=JSON.stringify(file);assert.equal(file.type,'13-omens-character');assert.equal(file.version,1);assert.doesNotMatch(json,/roomCode|playerId|reconnectToken|socketId|hostId|pendingCheck|"bag"|secret/);assert.equal(file.character.wounds,2);});
test('Character import preserves full state with new ID, no assignment, fixed story count and Omen invariant',()=>{const source=populated(),file=source.exportCharacter(source.getState().selectedCharacterId),{room,act}=setup();act('importCharacter',[file]);const c=room.gameState.characters[1];assert.notEqual(c.id,file.character.id);assert.ok([...room.players.values()].every(p=>p.assignedCharacterId!==c.id));assert.equal(room.gameState.storyCharacterCount,1);assert.equal(R.validateOmenEconomy(room.gameState),true);const out=S.createStore({storage:null,initialState:room.gameState}).exportCharacter(c.id);delete out.character.id;delete file.character.id;assert.deepEqual(out.character,file.character);});
for(const mutation of [f=>f.type='wrong',f=>f.version=99,f=>f.character.aspects[0].rating='Invalid',f=>f.character.aspects.shift(),f=>f.character.aspects.push({...f.character.aspects[9]}),f=>f.character.playerId='evil',f=>f.character.perks[0].socketId='evil',f=>f.character.perkUsage.bossy.secret='evil',f=>f.character.notes=42])test('Malformed character file rejects without partial creation: '+mutation.toString(),()=>{const s=fresh(),source=populated(),file=source.exportCharacter(source.getState().selectedCharacterId);mutation(file);const before=s.getState();assert.throws(()=>s.importCharacter(file));assert.deepEqual(s.getState(),before);});
test('Invalid JSON, six-character cap and Player import restriction',()=>{assert.throws(()=>JSON.parse('{invalid'));const {room,act}=setup(),s=populated(),file=s.exportCharacter(s.getState().selectedCharacterId);assert.throws(()=>act('importCharacter',[file],'p'));while(room.gameState.characters.length<6)act('addCharacter',[]);const before=structuredClone(room.gameState);assert.throws(()=>act('importCharacter',[file]),/maximum number/);assert.deepEqual(room.gameState,before);});
test('Host and Player sheet share layout and only Host gets correction buttons',()=>{const s=populated(),state=s.getState(),c=state.characters[0],host=Sheet.markup(state,c,true,'Host',true),player=Sheet.markup(state,c,true,'Bob',false);assert.match(host,/data-strain=/);assert.match(host,/data-disable=/);assert.doesNotMatch(player,/data-strain=|data-disable=|data-relief=/);assert.match(player,/SAVE CHARACTER/);assert.match(player,/data-rule/);});

test('Real sockets broadcast Player sheet saves to Host and preserve them on reconnect',async t=>{
  const {once}=require('node:events'),{io}=require('socket.io-client'),{createServer}=require('../server/server');
  const service=createServer({log:()=>{}}),sockets=[];
  service.server.listen(0,'127.0.0.1');await once(service.server,'listening');
  t.after(async()=>{sockets.forEach(s=>s.disconnect());await new Promise(resolve=>service.io.close(resolve));});
  const connect=async()=>{const socket=io(`http://127.0.0.1:${service.server.address().port}`,{forceNew:true,reconnection:false});sockets.push(socket);await once(socket,'connect');return socket;};
  const send=(socket,event,payload)=>new Promise((resolve,reject)=>socket.timeout(2000).emit(event,payload,(error,response)=>error?reject(error):resolve(response)));
  const h=await connect(),created=await send(h,'room:create',{}),p=await connect(),joined=await send(p,'room:join',{roomCode:created.room.code,displayName:'Bob'}),id=created.room.gameState.selectedCharacterId;
  await send(h,'player:assign-character',{playerId:joined.session.playerId,characterId:id});
  const aspects=structuredClone(created.room.gameState.characters[0].aspects);aspects[0].rating='Good';
  const broadcast=once(h,'room:state');
  const saved=await send(p,'game:action',{action:'editCharacter',args:[id,{aspects,perks:[{id:'bossy',name:'Bossy',notes:'',ruleKey:'bossy',disabled:false}],gear:[{id:'torch',name:'Flashlight',notes:''}]}],baseVersion:0});
  assert.equal(saved.ok,true);assert.deepEqual((await broadcast)[0].gameState,saved.room.gameState);
  p.disconnect();const p2=await connect(),reconnected=await send(p2,'room:reconnect',joined.session);assert.equal(reconnected.ok,true);assert.deepEqual(reconnected.room.gameState.characters,saved.room.gameState.characters);
  const stale=await send(p2,'game:action',{action:'editCharacter',args:[id,{name:'Stale'}],baseVersion:0});assert.equal(stale.error.code,'STALE_STATE');
});
test('Player editing defaults ON for existing schema-5 saves and rejects nonboolean settings',()=>{const state=fresh().getState();delete state.settings.allowPlayerCharacterEdits;const s=S.createStore({storage:null,initialState:state});assert.equal(s.getState().settings.allowPlayerCharacterEdits,true);assert.throws(()=>s.setSetting('allowPlayerCharacterEdits','yes'));});
test('Duplicate display names import successfully; insufficient Wound Omens rejects atomically',()=>{const s=populated(),file=s.exportCharacter(s.getState().selectedCharacterId);s.importCharacter(file);assert.equal(s.getState().characters.filter(c=>c.name==='Jasper').length,2);const state=s.getState();state.bag.omen=state.hostOmens;state.hostOmens=0;s.importState(state);const before=s.getState();assert.throws(()=>s.importCharacter(file),/not enough Host Omens/);assert.deepEqual(s.getState(),before);});
